###########################################################################
# 1. Dataset & paths
###########################################################################

data_path: "datasets/02-hands-on-geron/imdb"
checkpoint_dir: "checkpoints/"
tokenizer_path: "datasets/tokenizers/"  

max_seq_length: 500          # Geron: 500
# Type of pretrained tokenizer to use 
pretrained_tokenizer: "gpt2" 

# We use a pre-trained tokenizer
# max_vocab_size: 1000         


###########################################################################
# 2. Model Hyperparameters
###########################################################################

# Model hyperparameters: in order of significance
hidden_dim: 256              # Geron: 64
num_layers: 2                # Geron: 2
embedding_dim: 256           # Geron: 128
dropout: 0.2                 # Geron: 0.2

###########################################################################
# 3. Training Hyperparameters
###########################################################################

batch_size: 512              # Geron: 256             
learning_rate: 0.001         # Geron: torch.optim.NAdam(lr=0.001)
epochs: 5                  # Geron: 10
weight_decay: 0.001          # Geron: NOT used

###########################################################################
# 4. Training Flow
###########################################################################

patience: 3                  # 
gradient_clip_val: 1.0
monitor_metric: 'val_loss'